version: '3'
services:
  wyoming-piper:
    build:
      context: ./piper/
      dockerfile: NONGPU.Dockerfile
    ports:
      - "10200:10200"
    command: [ "--voice", "en_US-lessac-medium" ]
    restart: unless-stopped

  wyoming-whisper:
    build:
      context: ./whisper/
      dockerfile: NONGPU.Dockerfile
    ports:
      - "10300:10300"
    command: [ "--model", "tiny-int8", "--language", "en" ]
    restart: unless-stopped

  wyoming-openwakeword:
    build:
      context: ./openwakeword/
      dockerfile: NONGPU.Dockerfile
    ports:
      - "10400:10400"
    command: [ "--preload-model", "ok_nabu" ]
    restart: unless-stopped

